import {afterAll,afterEach,expect,test} from 'vitest';
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {App} from './App.jsx';
const nativeFetch=globalThis.fetch;
const origin=process.env.SKILLOBS_TEST_ORIGIN||'http://127.0.0.1:8776';
let cookie='';
// Real loopback API. Only relative-URL and browser-cookie transport are adapted.
globalThis.fetch=async(input,options={})=>{
 const headers=new Headers(options.headers);if(cookie)headers.set('cookie',cookie);
 const res=await nativeFetch(new URL(input,origin),{...options,headers});
 const next=res.headers.get('set-cookie');if(next)cookie=next.split(';')[0];return res;
};
afterEach(()=>cleanup());
afterAll(async()=>{cleanup();const session=await(await fetch('/api/session')).json();await fetch('/api/settings',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':session.csrf},body:JSON.stringify({locale:'zh-CN'})});globalThis.fetch=nativeFetch});
test('live API locale change preserves filter, draft, navigation and refresh recovery',async()=>{
 localStorage.clear();sessionStorage.clear();location.hash='#settings';
 const boot=await(await fetch('/api/session')).json();await fetch('/api/settings',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':boot.csrf},body:JSON.stringify({locale:'zh-CN'})});
 const app=render(<App/>);
 await screen.findByLabelText('时区');
 fireEvent.change(screen.getByLabelText('时区'),{target:{value:'Asia/Tokyo'}});
 fireEvent.click(screen.getByRole('button',{name:'观测记录',exact:true}));
 fireEvent.change(screen.getByLabelText('搜索运行、Skill 或 ID…'),{target:{value:'pilot-marker'}});
 fireEvent.click(screen.getByRole('button',{name:'English',exact:true}));
 await screen.findByLabelText('Search runs, skills, or IDs…');
 expect(screen.getByLabelText('Search runs, skills, or IDs…').value).toBe('pilot-marker');
 expect(location.hash).toBe('#observations');
 fireEvent.click(screen.getByRole('button',{name:'Settings',exact:true}));
 await screen.findByLabelText('Time zone');expect(screen.getByLabelText('Time zone').value).toBe('Asia/Tokyo');
 await waitFor(async()=>{const current=await(await fetch('/api/state')).json();expect(current.settings.locale).toBe('en')});
 app.unmount();render(<App/>);
 await screen.findByLabelText('Time zone');expect(screen.getByLabelText('Time zone').value).toBe('Asia/Tokyo');
 fireEvent.click(screen.getByRole('button',{name:'Observations',exact:true}));
 await screen.findByLabelText('Search runs, skills, or IDs…');expect(screen.getByLabelText('Search runs, skills, or IDs…').value).toBe('pilot-marker');
 fireEvent.click(screen.getByRole('button',{name:'中文',exact:true}));
 await screen.findByLabelText('搜索运行、Skill 或 ID…');expect(screen.getByLabelText('搜索运行、Skill 或 ID…').value).toBe('pilot-marker');
 fireEvent.click(screen.getByRole('button',{name:'设置',exact:true}));
 await screen.findByLabelText('时区');expect(screen.getByLabelText('时区').value).toBe('Asia/Tokyo');
});

test('live lifecycle catalog and usage keep stage evidence and recover filters',async()=>{
 localStorage.clear();location.hash='#skills';
 const boot=await(await fetch('/api/session')).json();await fetch('/api/settings',{method:'POST',headers:{'content-type':'application/json','x-csrf-token':boot.csrf},body:JSON.stringify({locale:'zh-CN'})});
 const app=render(<App/>);
 await screen.findByText('fixture-receipt-check');
 fireEvent.change(screen.getByLabelText('搜索能力、项目、会话或场景'),{target:{value:'no-such-capability'}});
 await screen.findByText('暂无匹配记录');
 fireEvent.click(screen.getByRole('button',{name:'清除筛选'}));
 await screen.findByText('fixture-receipt-check');
 fireEvent.click(screen.getByRole('button',{name:'查看',exact:true}));
 const detail=await screen.findByRole('dialog');
 detail.focus();fireEvent.keyDown(document,{key:'Tab',shiftKey:true});
 expect(detail.contains(document.activeElement)).toBe(true);
 expect(document.activeElement.textContent).toBe('关闭');
 fireEvent.keyDown(document,{key:'Tab'});
 expect(document.activeElement.textContent).toBe('中文');
 expect(screen.getAllByText('UNKNOWN').length).toBeGreaterThan(0);
 expect(screen.getByLabelText('各阶段独立计数').textContent).toContain('已执行1');
 expect(screen.getByLabelText('各阶段独立计数').textContent).toContain('已验收0');
 fireEvent.keyDown(document,{key:'Escape'});
 fireEvent.click(screen.getByRole('button',{name:'复用记录',exact:true}));
 await screen.findByText('fixture: metadata import');
 fireEvent.change(screen.getByLabelText('状态或阶段'),{target:{value:'accepted'}});
 await screen.findByText('暂无匹配记录');
 app.unmount();render(<App/>);
 await screen.findByLabelText('状态或阶段');
 expect(screen.getByLabelText('状态或阶段').value).toBe('accepted');
 fireEvent.click(screen.getByRole('button',{name:'English',exact:true}));
 await screen.findByLabelText('Status or stage');
 expect(screen.getByLabelText('Status or stage').value).toBe('accepted');
 expect(screen.getByText('No matching records')).toBeTruthy();
});
